platform :ios, '10.0'
use_frameworks!

target 'TPFeatureTag_Example' do
  pod 'TPFeatureTag', :path => '../'

  target 'TPFeatureTag_Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 7.3.1'
  end
end
