# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods --pre # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TPFeatureTag.xcworkspace -scheme TPFeatureTag-Example -sdk iphonesimulator12.0 -destination "platform=iOS Simulator,name=iPhone XS Max" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

